In [3]:
g=[4,5,33,3]

In [4]:
print(g)

[4, 5, 33, 3]


In [1]:
import numpy as np 

In [6]:
np.__version__

'1.23.0'

In [11]:
list = ['A','B','C']
print(list[-1])


C


In [8]:
list = ['A','B','C']
list[0]='K'
list[2]='C'
list.append('5')
print(list)


['K', 'B', 'C', '5']


In [14]:
#Creating arrays from python lists 
np.array([2,4,6,.8,10])

array([ 2. ,  4. ,  6. ,  0.8, 10. ])

In [13]:
#Numpy arrays contain the same type of data 
np.array([2.5, 4, 6.7, 8,10])

array([ 2.5,  4. ,  6.7,  8. , 10. ])

In [19]:
#Explicitly set the datatype using `dtype` keyword. 
np.array([3,4,32,6],dtype='float32')

array([ 3.,  4., 32.,  6.], dtype=float32)

In [5]:
np.array([4,5623,34],dtype='float32')

array([4.000e+00, 5.623e+03, 3.400e+01], dtype=float32)

In [6]:
np.array([3,4,32,6],dtype='float32')


array([ 3.,  4., 32.,  6.], dtype=float32)

In [4]:
#Especially for large arrays,it is more efficient to create arrays from scratch using routines built into NumPy.
import numpy as np 
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [5]:
np.zeros(10, dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#creating a 3x4 floating-point array filled with ones
np.ones((3,4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [11]:
np.full((34,4),3.1416)

array([[3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 

In [13]:
np.full((4,5),'hi')

array([['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi']], dtype='<U2')

In [22]:
#Create an array filled with linear sequence. 
np.arange(0, 528, 9)

array([  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108,
       117, 126, 135, 144, 153, 162, 171, 180, 189, 198, 207, 216, 225,
       234, 243, 252, 261, 270, 279, 288, 297, 306, 315, 324, 333, 342,
       351, 360, 369, 378, 387, 396, 405, 414, 423, 432, 441, 450, 459,
       468, 477, 486, 495, 504, 513, 522])

In [7]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [3]:
np.linespace(0,1,5)

NameError: name 'np' is not defined

In [8]:
np.random.random((3,9))

array([[0.86290608, 0.61861028, 0.24174073, 0.20900206, 0.79141603,
        0.62516228, 0.07986121, 0.45760327, 0.49782502],
       [0.22396025, 0.34982099, 0.46482548, 0.90677297, 0.82900295,
        0.89637406, 0.1092487 , 0.36581181, 0.23666938],
       [0.00695348, 0.52542607, 0.07251582, 0.32225171, 0.62311283,
        0.19930158, 0.86580352, 0.34777339, 0.21164137]])

In [9]:
np.random.normal(0,1,(3,3))

array([[-0.17063728, -1.01533819, -0.62072112],
       [ 0.22162006, -1.20653605,  0.58649446],
       [-1.42049925,  0.37077366, -1.05287375]])

In [15]:
np.random.randint(0,10,(3,3))

array([[9, 7, 6],
       [3, 1, 1],
       [1, 5, 9]])

In [16]:
#5x5 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(65)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

In [2]:
import numpy as np 
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [41]:
x1

array([5, 0, 3, 3, 7, 9])

In [44]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [46]:
print(np.random.randint(23, size=12))

[10 22 11  8 11  2 19 16  0 22  0  6]


In [56]:
print(np.random.randint(32, size=(2,12,343)))

[[[29  2  5 ...  4 17 18]
  [13 30 13 ...  1 11 15]
  [30 12 15 ...  3  5  7]
  ...
  [21  7 17 ... 25 27 24]
  [31 26 31 ... 30 25  7]
  [10 12  4 ... 10 21  0]]

 [[19 31 24 ... 15  4  6]
  [28 10 23 ... 25 19 30]
  [ 8  7 29 ...  6 12 15]
  ...
  [25 26 21 ... 29 27 16]
  [25 20 22 ... 22 20 13]
  [ 1  0  9 ... 25 23 17]]]


In [57]:
print("x3 ndim: ", x3.ndim)

x3 ndim:  3


In [58]:
print("x3 shape,size:", x3.shape ,x3.size)

x3 shape,size: (3, 4, 5) 60


In [60]:
print("x3 shape, size, bytes:", x3.shape ,x3.size,x3.nbytes)

x3 shape, size, bytes: (3, 4, 5) 60 240


In [1]:
x2[2,-1]

NameError: name 'x2' is not defined

In [3]:
import numpy as np 
x=np.arange(32)

In [4]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [5]:
x[:5]

array([0, 1, 2, 3, 4])

In [6]:
x[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [7]:
x[3:7]

array([3, 4, 5, 6])

In [8]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [9]:
x[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [11]:
x[:3,:2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [6]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [7]:
print(x2[0,:])

[3 5 2 4]


In [8]:
print(x2[:,0])

[3 7 1]


In [3]:
a = np.arange(1, 10).reshape((3, 3))

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
x = np.array([4,53,60])
y = np.array([43])
b = np.concatenate([x,y])

In [7]:
b

array([ 4, 53, 60, 43])

In [8]:
print(b)

[ 4 53 60 43]


In [10]:
f = [6,5]

In [11]:
b = np.concatenate([x,y,f])

In [12]:
b

array([ 4, 53, 60, 43,  6,  5])

In [14]:
#2D array
h = np.array([[54,53,22],[45,2,9]])

In [15]:
h

array([[54, 53, 22],
       [45,  2,  9]])

In [16]:
np.concatenate([h,h])

array([[54, 53, 22],
       [45,  2,  9],
       [54, 53, 22],
       [45,  2,  9]])

In [21]:
#mix dimenstion 
x = np.array([5,44])
u = np.array([[4,5,422],[222,7,5]])

np.vstack([x,u])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
 [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

In [23]:
x = np.array([1, 2, 3])
y = np.array([[9, 8, 7],
 [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, y])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [31]:
x = [3,34,222,5,4,334,222,244,57]
a,b,c = np.split(x,[3,7])
print(a,b,c)

[  3  34 222] [  5   4 334 222] [244  57]


In [42]:
grid = np.arange(64).reshape((8,8))

In [43]:
grid

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [55]:
a = np.arange(0,39).reshape((13,3))

In [51]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

In [58]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
